# USAGE: docker-compose -f docker-compose-get_cert.yml up
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-no-ssl.conf:/etc/nginx/nginx.conf
      - letsencrypt_data:/etc/letsencrypt

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    depends_on:
      - nginx
    volumes:
      - letsencrypt_data:/etc/letsencrypt
    command: certonly --agree-tos --webroot -w /etc/letsencrypt/ -m yoshi@chubachi.net -d km.co-creation.info

volumes:
  letsencrypt_data:
    external: true
  
